import type { Translation } from './types';

export const zh: Translation = {
  'provider.deepseek.detail': '通用对话与深度推理，2 个模型',
  'provider.minimax.detail': '深度推理，支持超长上下文，7 个模型',

  'model.deepseek-v4-flash.detail': '快速通用模型',
  'model.deepseek-v4-pro.detail': '深度推理模型',
  'model.minimax-text-01.detail': '超长上下文，支持图像',
  'model.minimax-m1.detail': '深度推理模型',
  'model.minimax-m2.detail': '深度推理模型',
  'model.minimax-m2.1.detail': '深度推理模型',
  'model.minimax-m2.1-highspeed.detail': '深度推理，高速版',
  'model.minimax-m2.5.detail': '深度推理模型',
  'model.minimax-m2.5-highspeed.detail': '深度推理，高速版',
  'model.minimax-m2.7.detail': '深度推理模型',
  'model.minimax-m2.7-highspeed.detail': '深度推理，高速版',

  'auth.keyInput': '请输入 {0} API Key',
  'auth.keyInputHinted': '请输入 {0} API Key（格式：{1}）',
  'auth.keyHint': 'sk-...',
  'auth.keyRequired': '请输入有效的 API Key',
  'auth.keyStored': '{0} API Key 已安全保存。',
  'auth.chooseProvider': '选择提供商',
  'auth.chooseClearTarget': '选择要清除 API Key 的提供商',
  'auth.noKeysFound': '当前没有已配置的 API Key',

  'think.label': '思考模式',
  'think.none': '无',
  'think.none.hint': '无推理步骤，输出最快',
  'think.high': '高',
  'think.high.hint': '适合日常编程任务',
  'think.max': '最大',
  'think.max.hint': '全力推理，复杂问题最佳',

  'vision.chooseProxy': '选择图像描述模型（默认 {0}）',
  'vision.activeLabel': '当前',
  'vision.disableCmd': '禁用视觉代理',
  'vision.offLabel': '已禁用',
  'vision.proxyLabel': '视觉代理：{0}',
  'vision.proxySkipped': '无可用视觉模型，图片已忽略。',
  'vision.proxyFault': '视觉代理异常：',
  'vision.providerTag': '提供商：{0}',

  'err.http.401': '认证失败（401）。',
  'err.http.402': '额度不足（402）。',
  'err.http.429': '请求过于频繁（429），请稍后重试。',
  'err.http.500': '服务器内部错误（500）。',
  'err.http.503': '服务暂时不可用（503）。',
  'err.network.dns': '无法连接到 {0}，请检查网络和 API 地址。',
  'err.network.aborted': '请求已取消。',
  'err.network.timeout': '请求超时，请重试。',
  'err.action.keys': '前往 API Keys',
  'err.action.usage': '查看用量',
  'err.action.status': '查看状态',
  'err.action.logs': '查看日志',
};
