import type { ModelItem } from '../types';
import { ZHIPU } from './provider';
import { ZHIPU_THINKING, ZHIPU_GLM52_THINKING } from '../defines';

const BM_THINK_BASE = {
  family: 'glm',
  provider: ZHIPU,
  thinking: true,
  imageInput: false,
  maxTools: 128,
  thinkingConfig: ZHIPU_THINKING,
};

const BM_GLM52_BASE = {
  family: 'glm',
  provider: ZHIPU,
  thinking: true,
  imageInput: false,
  maxTools: 128,
  thinkingConfig: ZHIPU_GLM52_THINKING,
};

const BM_PLAIN_BASE = {
  family: 'glm',
  provider: ZHIPU,
  thinking: false,
  imageInput: false,
  maxTools: 128,
};

const BM_VISION_THINK_BASE = {
  family: 'glm',
  provider: ZHIPU,
  thinking: true,
  imageInput: true,
  maxTools: 128,
  thinkingConfig: ZHIPU_THINKING,
};

const BM_VISION_PLAIN_BASE = {
  family: 'glm',
  provider: ZHIPU,
  thinking: false,
  imageInput: true,
  maxTools: 128,
};

export const ZHIPU_GLM_4_7: ModelItem = {
  ...BM_THINK_BASE,
  id: 'glm-4.7',
  label: 'GLM-4.7',
  apiId: 'glm-4.7',
  version: '4.7',
  maxInputTokens: 200_000,
  maxOutputTokens: 128_000,
  detailKey: 'model.glm-4.7.detail',
} as ModelItem;

export const ZHIPU_GLM_5_2: ModelItem = {
  ...BM_GLM52_BASE,
  id: 'glm-5.2',
  label: 'GLM-5.2',
  apiId: 'glm-5.2',
  version: '5.2',
  maxInputTokens: 872_000,
  maxOutputTokens: 128_000,
  detailKey: 'model.glm-5.2.detail',
  pricing: {
    USD: { cacheHitInput: 0.26, cacheMissInput: 1.4, output: 4.4 },
    CNY: { cacheHitInput: 2, cacheMissInput: 8, output: 28 },
  },
  priceCategory: 'high',
} as ModelItem;

export const ZHIPU_GLM_5_1: ModelItem = {
  ...BM_THINK_BASE,
  id: 'glm-5.1',
  label: 'GLM-5.1',
  apiId: 'glm-5.1',
  version: '5.1',
  maxInputTokens: 200_000,
  maxOutputTokens: 128_000,
  detailKey: 'model.glm-5.1.detail',
  pricing: {
    USD: { cacheHitInput: 0.26, cacheMissInput: 1.4, output: 4.4 },
    CNY: {
      cacheHitInput: '1.3(<32K)/2(>=32K)',
      cacheMissInput: '6(<32K)/8(>=32K)',
      output: '24(<32K)/28(>=32K)',
    },
  },
  priceCategory: 'high',
} as ModelItem;

export const ZP_MODELS: readonly ModelItem[] = [
  ZHIPU_GLM_5_2,
  ZHIPU_GLM_5_1,
  {
    ...BM_THINK_BASE,
    id: 'glm-5',
    label: 'GLM-5',
    apiId: 'glm-5',
    version: '5',
    maxInputTokens: 200_000,
    maxOutputTokens: 128_000,
    detailKey: 'model.glm-5.detail',
    pricing: {
      USD: { cacheHitInput: 0.2, cacheMissInput: 1, output: 3.2 },
      CNY: {
        cacheHitInput: '1(<32K)/1.5(>=32K)',
        cacheMissInput: '4(<32K)/6(>=32K)',
        output: '18(<32K)/22(>=32K)',
      },
    },
    priceCategory: 'medium',
  },
  {
    ...BM_THINK_BASE,
    id: 'glm-5-turbo',
    label: 'GLM-5-Turbo',
    apiId: 'glm-5-turbo',
    version: '5',
    maxInputTokens: 200_000,
    maxOutputTokens: 128_000,
    detailKey: 'model.glm-5-turbo.detail',
    pricing: {
      USD: { cacheHitInput: 0.24, cacheMissInput: 1.2, output: 4.0 },
      CNY: {
        cacheHitInput: '1.2(<32K)/1.8(>=32K)',
        cacheMissInput: '5(<32K)/7(>=32K)',
        output: '22(<32K)/26(>=32K)',
      },
    },
    priceCategory: 'high',
  },
  ZHIPU_GLM_4_7,
  {
    ...BM_PLAIN_BASE,
    id: 'glm-4.7-flashx',
    label: 'GLM-4.7-FlashX',
    apiId: 'glm-4.7-flashx',
    version: '4.7',
    maxInputTokens: 200_000,
    maxOutputTokens: 128_000,
    detailKey: 'model.glm-4.7-flashx.detail',
  },
  {
    ...BM_THINK_BASE,
    id: 'glm-4.6',
    label: 'GLM-4.6',
    apiId: 'glm-4.6',
    version: '4.6',
    maxInputTokens: 200_000,
    maxOutputTokens: 128_000,
    detailKey: 'model.glm-4.6.detail',
  },
  {
    ...BM_PLAIN_BASE,
    id: 'glm-4.5-air',
    label: 'GLM-4.5-Air',
    apiId: 'glm-4.5-air',
    version: '4.5',
    maxInputTokens: 128_000,
    maxOutputTokens: 96_000,
    detailKey: 'model.glm-4.5-air.detail',
  },
  {
    ...BM_PLAIN_BASE,
    id: 'glm-4.5-airx',
    label: 'GLM-4.5-AirX',
    apiId: 'glm-4.5-airx',
    version: '4.5',
    maxInputTokens: 128_000,
    maxOutputTokens: 96_000,
    detailKey: 'model.glm-4.5-airx.detail',
  },
  {
    ...BM_PLAIN_BASE,
    id: 'glm-4-long',
    label: 'GLM-4-Long',
    apiId: 'glm-4-long',
    version: '4',
    maxInputTokens: 1_000_000,
    maxOutputTokens: 4_096,
    detailKey: 'model.glm-4-long.detail',
  },
  {
    ...BM_PLAIN_BASE,
    id: 'glm-4-flashx-250414',
    label: 'GLM-4-FlashX-250414',
    apiId: 'glm-4-flashx-250414',
    version: '4',
    maxInputTokens: 128_000,
    maxOutputTokens: 16_384,
    detailKey: 'model.glm-4-flashx-250414.detail',
  },
  {
    ...BM_PLAIN_BASE,
    id: 'glm-4.7-flash',
    label: 'GLM-4.7-Flash',
    apiId: 'glm-4.7-flash',
    version: '4.7',
    maxInputTokens: 200_000,
    maxOutputTokens: 128_000,
    detailKey: 'model.glm-4.7-flash.detail',
  },
  {
    ...BM_PLAIN_BASE,
    id: 'glm-4.5-flash',
    label: 'GLM-4.5-Flash',
    apiId: 'glm-4.5-flash',
    version: '4.5',
    maxInputTokens: 128_000,
    maxOutputTokens: 96_000,
    detailKey: 'model.glm-4.5-flash.detail',
  },
  {
    ...BM_PLAIN_BASE,
    id: 'glm-4-flash-250414',
    label: 'GLM-4-Flash-250414',
    apiId: 'glm-4-flash-250414',
    version: '4',
    maxInputTokens: 128_000,
    maxOutputTokens: 16_384,
    detailKey: 'model.glm-4-flash-250414.detail',
  },
  {
    ...BM_VISION_THINK_BASE,
    id: 'glm-5v-turbo',
    label: 'GLM-5V-Turbo',
    apiId: 'glm-5v-turbo',
    version: '5',
    maxInputTokens: 200_000,
    maxOutputTokens: 128_000,
    detailKey: 'model.glm-5v-turbo.detail',
  },
  {
    ...BM_VISION_THINK_BASE,
    id: 'glm-4.6v',
    label: 'GLM-4.6V',
    apiId: 'glm-4.6v',
    version: '4.6',
    maxInputTokens: 128_000,
    maxOutputTokens: 32_768,
    detailKey: 'model.glm-4.6v.detail',
  },
  {
    ...BM_VISION_PLAIN_BASE,
    id: 'glm-ocr',
    label: 'GLM-OCR',
    apiId: 'glm-ocr',
    version: '4',
    maxInputTokens: 128_000,
    maxOutputTokens: 4_096,
    detailKey: 'model.glm-ocr.detail',
  },
  {
    ...BM_VISION_THINK_BASE,
    id: 'glm-4.1v-thinking-flashx',
    label: 'GLM-4.1V-Thinking-FlashX',
    apiId: 'glm-4.1v-thinking-flashx',
    version: '4.1',
    maxInputTokens: 64_000,
    maxOutputTokens: 16_384,
    detailKey: 'model.glm-4.1v-thinking-flashx.detail',
  },
  {
    ...BM_VISION_PLAIN_BASE,
    id: 'glm-4.6v-flash',
    label: 'GLM-4.6V-Flash',
    apiId: 'glm-4.6v-flash',
    version: '4.6',
    maxInputTokens: 128_000,
    maxOutputTokens: 32_768,
    detailKey: 'model.glm-4.6v-flash.detail',
  },
  {
    ...BM_VISION_THINK_BASE,
    id: 'glm-4.1v-thinking-flash',
    label: 'GLM-4.1V-Thinking-Flash',
    apiId: 'glm-4.1v-thinking-flash',
    version: '4.1',
    maxInputTokens: 64_000,
    maxOutputTokens: 16_384,
    detailKey: 'model.glm-4.1v-thinking-flash.detail',
  },
  {
    ...BM_VISION_PLAIN_BASE,
    id: 'glm-4v-flash',
    label: 'GLM-4V-Flash',
    apiId: 'glm-4v-flash',
    version: '4',
    maxInputTokens: 16_384,
    maxOutputTokens: 1_024,
    detailKey: 'model.glm-4v-flash.detail',
  },
] as ModelItem[];
